# Generated by Django 4.2.5 on 2023-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_address_district_address_pin_address_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuser',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
