# Generated by Django 4.2.5 on 2023-10-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_uuser_is_google_alter_uuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
