# Generated by Django 4.2.5 on 2023-10-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_work_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
