# Generated by Django 4.2.5 on 2023-10-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_delete_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuser',
            name='field',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
