# Generated by Django 4.2.5 on 2023-10-20 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=100000, message='PiN should have 6 numbers'), django.core.validators.MaxValueValidator(limit_value=999999, message='PIN should have only 6 numbers')]),
        ),
    ]
