# Generated by Django 4.2.5 on 2023-10-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0002_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_at',
            new_name='commented_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='posted_by',
            new_name='commented_by',
        ),
    ]
