# Generated by Django 4.2.5 on 2023-10-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0003_rename_posted_at_comment_commented_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
