# Generated by Django 4.2.5 on 2023-11-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
