# Generated by Django 4.2.5 on 2023-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_components', '0002_banner_description_banner_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(unique=True),
        ),
    ]
